### ISSUE TITLE
StackOverflowError when calling ComposableFutures.batchUnordered

### ISSUE THREAD

**Issue by ahadadi** [outbrain/ob1k#67] opened 2017-02-06 20:23 UTC
Reproduction:
`
ComposableFutures.batchUnordered(Collections.nCopies(2000, 1), 1, result -> ComposableFutures.submit(() -> result)).get();
`

**Comment by marenzo** [comment] 2017-03-17 17:57
duplicate of #66

**Closed by marenzo** 2017-03-17 17:57 UTC
